apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-3
  template:
    metadata:
      labels:
        app: app-3
    spec:
      containers:
        - name: app-3
          image: miguelangelmolina/app-3
          ports:
            - containerPort: 3003
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
