apiVersion: v1 
kind: Service 
metadata:
  name: app-3  
spec: 
  selector:
    app: app-3 
  ports:
    - protocol: TCP
      port: 83 # Puerto del servicio expuesto (para acceder desde fuera del clúster)
      targetPort: 3003  # Puerto en el contenedor donde se ejecuta la aplicación
  type: LoadBalancer  # Tipo de servicio (NodePort para acceder desde fuera del clúster)
