apiVersion: v1
kind: Service
metadata:
  name: app-1
spec:
  selector:
    app: app-1
  ports:
    - protocol: TCP
      port: 81  # Puerto del servicio expuesto (para acceder desde fuera del clúster)
      targetPort: 3000  # Puerto en el contenedor donde se ejecuta la aplicación
  type: LoadBalancer  # Tipo de servicio (NodePort para acceder desde fuera del clúster)
