apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-2-hpa
spec:
  scaleTargetRef: # Referencia al deployment
    apiVersion: apps/v1
    kind: Deployment
    name: app-2
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
