apiVersion: v1 # Versión de la API de Kubernetes
kind: Service # Tipo de recurso
metadata:
  name: app-2
spec:
  selector: # Selecciona los pods que pertenecen a este servicio
    app: app-2
  ports:  # Puertos expuestos por el servicio
    - protocol: TCP # Protocolo de comunicación
      port: 82  # Puerto del servicio expuesto (para acceder desde fuera del clúster)
      targetPort: 3001  # Puerto en el contenedor donde se ejecuta la aplicación
  type: LoadBalancer  # Tipo de servicio (NodePort para acceder desde fuera del clúster)
